(executable
 (name server)
 (libraries containers str yojson lwt cohttp cohttp-lwt cohttp-lwt-unix webmachine sexplib0 diplostats)
 (promote (until-clean) (into ".."))
 (modules Server)
)

(executable
 (name main)
 (libraries containers str yojson diplostats)
 (promote (until-clean) (into ".."))
 (modules Main)
)

(executable
 (name test)
 (libraries containers str yojson diplostats)
 (promote (until-clean) (into ".."))
 (modules Test)
)

(env (dev (flags (:standard -warn-error -A))))
